### ISSUE TITLE
Typescript generation crashes with stack overflow error

### ISSUE THREAD

**Issue by HowCome** [RicoSuter/NSwag#2686]
The attached json document causes stack overflow in tscript generator if Generate DTO is set to true.
[minimal.zip](https://github.com/RicoSuter/NSwag/files/4201830/minimal.zip)

**Comment by RicoSuter** [comment]
This is bad and must be fixed in NJsonSchema.. i suppose you dont have a stacktrace?

**Comment by HowCome** [comment]
`>	NSwag.CodeGeneration.TypeScript.dll!NSwag.CodeGeneration.TypeScript.Models.TypeScriptFileTemplateModel.TypeScriptFileTemplateModel(System.Collections.Generic.IEnumerable<NJsonSchema.CodeGeneration.CodeArtifact> clientTypes, System.Collections.Generic.IEnumerable<NJsonSchema.CodeGeneration.CodeArtifact> dtoTypes, NSwag.OpenApiDocument document, NJsonSchema.CodeGeneration.TypeScript.TypeScriptExtensionCode extensionCode, NSwag.CodeGeneration.TypeScript.TypeScriptClientGeneratorSettings settings, NJsonSchema.CodeGeneration.TypeScript.TypeScriptTypeResolver resolver) Line 49	C#
 	NSwag.CodeGeneration.TypeScript.dll!NSwag.CodeGeneration.TypeScript.TypeScriptClientGenerator.GenerateFile(System.Collections.Generic.IEnumerable<NJsonSchema.CodeGeneration.CodeArtifact> clientTypes, System.Collections.Generic.IEnumerable<NJsonSchema.CodeGeneration.CodeArtifact> dtoTypes, NSwag.CodeGeneration.ClientGeneratorOutputType outputType) Line 96	C#
 	NSwag.CodeGeneration.dll!NSwag.CodeGeneration.ClientGeneratorBase<NSwag.CodeGeneration.TypeScript.Models.TypeScriptOperationModel, NSwag.CodeGeneration.TypeScript.Models.TypeScriptParameterModel, NSwag.CodeGeneration.TypeScript.Models.TypeScriptResponseModel>.GenerateFile(NSwag.CodeGeneration.ClientGeneratorOutputType outputType) Line 89	C#
 	NSwag.CodeGeneration.dll!NSwag.CodeGeneration.ClientGeneratorBase<NSwag.CodeGeneration.TypeScript.Models.TypeScriptOperationModel, NSwag.CodeGeneration.TypeScript.Models.TypeScriptParameterModel, NSwag.CodeGeneration.TypeScript.Models.TypeScriptResponseModel>.GenerateFile() Line 65	C#
 	NSwag.Commands.dll!NSwag.Commands.CodeGeneration.SwaggerToTypeScriptClientCommand.RunAsync.AnonymousMethod__147_0() Line 390	C#
`

**Comment by DDtMM** [comment]
I had the same problem with version 13.7.0 and version 10.1.26 of NJsonSchema.  I then tried downgrading and the problem persisted.  My schema and the one provided by @HowCome were very different - he was using swagger 2.0, me OpenApi 3.1.  That actually made it easy to find the one glaring thing we had in common.  Under definitions/components.schemas we both had the following:

```
      "JToken": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/JToken"
        }
      }
```

When I took this out the problem went away.
