### ISSUE TITLE
NSwagStudio automatic update error

### ISSUE THREAD

**Issue by bcronje** [RicoSuter/NSwag#2802]
I keep getting the following error when doing the automatic update for NSwagStudio:

![image](https://user-images.githubusercontent.com/462097/79487085-f7e7fb00-8017-11ea-82a1-93eabae1cb9e.png)

Current version is 13.3 and it is attempting to upgrade to v13.4.1

**Comment by natsuo** [comment]
Probably related:
The NSwagStudio .MSI package link doesn't seem to be working at the moment. Gives a BlobNotFound error. Is there a problem with the latest build?

**Comment by RicoSuter** [comment]
Should be fixed now. There was a problem with the release.

**Comment by bcronje** [comment]
@RicoSuter I just tested the automatic upgrade from v13.4.1 to v13.4.2 and I'm still getting the same error as per the screenshot. It does seem to download the update file as it has the "Downloading..." popup up for a while and I can see through networking monitor that a download is in progress, before the error popup appears.

**Comment by bcronje** [comment]
Or should I manually upgrade to 13.4.2 and then going forward automatic updates should work?

**Comment by RicoSuter** [comment]
It worked for me - open studio, download and install. But you can do it manually and then you'll get new updates, yes.

**Comment by bcronje** [comment]
Thanks, I manually updated.

Thank you for NSwag and toolset, first project I'm using it and it's been a great tool.
