### ISSUE TITLE
Generated typescript file can not transpile with rxjs 7.0

### ISSUE THREAD

**Issue by MichaelBrimer** [RicoSuter/NSwag#3073]
Shifting from rxjs 6.6 to rxjs 7.0 gives errors in generated typescript file e.g.

error TS2322: Type 'Observable<unknown>' is 
not assignable to type 'Observable<Job[]>'.
  Type 'unknown' is not assignable to type 'Job[]'.
          return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
              return this.processGetMeasurements(response_);
                  return <Observable<Job[]>><any>_observableThrow(response_);

**Comment by RicoSuter** [comment]
Is this a breaking change in RxJS 7.0?

**Comment by MichaelBrimer** [comment]
Since major version is changed from 6 to 7 there are breaking changes. 
I think the issue is because of better checking, because of newer typescript version.
RxJs is in 7.0.0-beta.7, but I know that Google is using it internally and it should be very stable.
Angular released a new version 2 weeks after typescript 4.0, which used typescript 4.0, so it is very possible that the same will happen with RxJs 7

**Comment by asadsahi** [comment]
Angular 13 is released now. I am having same issue with upgrade to RXJS 7. Looking forward for a resolution. Thanks

**Comment by rgiosa** [comment]
+1

**Comment by asadsahi** [comment]
@rgiosa looking at the errors with rxjs 7 it isn't obvious what is causing these error. Types from controller do match with the client typescript file it produces. Any chance it can be looked at just in case I am wondering it could be a quick fix? Thanks

**Comment by RicoSuter** [comment]
Is this fixed with NSwag v13.14.1?

**Comment by asadsahi** [comment]
@RicoSuter I can't seem to see this as fixed in 13.14.1.  I have tried lifting rxjs version in compiler settings as:

`"rxJsVersion": 7.4,`

but looks the same error:

Here is the snippet of one error:
![image](https://user-images.githubusercontent.com/3470892/141447032-8ddfed46-78fd-4088-a52d-bf43abed79b9.png)

**Comment by asadsahi** [comment]
same issue with `13.14.2`, as I am too anxious to try this fix :)

**Comment by RicoSuter** [comment]
I would expect that this actually works:

https://github.com/RicoSuter/NSwag/pull/3567
https://github.com/RicoSuter/NSwag/pull/3670
https://github.com/RicoSuter/NSwag/pull/3544
https://github.com/RicoSuter/NSwag/pull/3482

**Comment by asadsahi** [comment]
@RicoSuter not sure what am I missing here. I have tried with 13.14.3 and `rxJsVersion: 7`, but it compiles client typescript file with the same errors, falling back to rxjs 6.x works :(. Any pointers?

**Comment by wratho** [comment]
rxjs 7 and 13.14.2 still do not work together. i have updated the configs to point to TS 4.4 and rxjs 7.4. still no good.

**Comment by alvarosinmarca** [comment]
rxjs 7 and 13.14.3 not work. 

Angular 13 have mandatory: rxjs >= 7

Please fix this :(

![image](https://user-images.githubusercontent.com/9324962/141757777-dd5cd5d2-03cb-42c0-87eb-e4c0d3e4095a.png)

**Comment by wratho** [comment]
> rxjs 7 and Nswag 13.14.3 not work.
> 
> Angular 13 have mandatory: rxjs >= 7
> 
> Please fix this :(
> 
> Temporal fix: Replace `<any>null` for `empty` in output file generated for Nswag ![image](https://user-images.githubusercontent.com/9324962/141759894-d399743d-428d-4506-a7c4-d2ceb5ffebde.png)

angular 13 should work without rxjs 7 btw. but we still do need this fixed. rxjs 7 has benefits people will want sooner than later.

**Comment by wratho** [comment]
update to 13.14.4. i didn't notice any generation changes therefore still broken.

Please let me know if there are any config changes we should be tweaking between versions.

**Comment by egrassinode** [comment]
I'm experiencing this issue too:
![immagine](https://user-images.githubusercontent.com/52748769/142015884-176c9922-49d9-48cc-a20d-2ee1bac6c220.png)

Generated file using the NSwag toolchain v13.14.4.0 (NJsonSchema v10.5.2.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)

with `angular@12.2.13`, `rxjs@7.4.0` and `typescript@4.2.3`

**Comment by wratho** [comment]
Update to 13.14.5, rebuilt all of our APIs with NSwag, i see 0 generation changes unfortunately so we are still broken. Please let me know if there is a configuration change we should be trying.

**Comment by rhegner** [comment]
Still not working with NSwag 13.14.7.
Is someone working on this?
Since the nswag configuration already contains the rxjs version, it should be relatively easy to generate code that works with rxjs 7 without potentially breaking older code with pre-v7 rxjs - or am I missing something here?

**Comment by wratho** [comment]
if i had to guess he will likely be targeting a fix for version 14? But that might be a while off.

**Comment by konstantin-kuda** [comment]
I have the same problem

**Comment by RicoSuter** [comment]
This PR fixed it for me: https://github.com/RicoSuter/NSwag/pull/3780
It's live with v13.15.0

**Comment by asadsahi** [comment]
Thanks @RicoSuter , Yes, this has fixed for me as well. RxJs 7 works with nswag v13.15.0.

**Comment by vpetrusevici** [comment]
Hmm. I still have a problem with 7.0 
![image](https://user-images.githubusercontent.com/40790510/145117783-d1f07434-4f78-4393-84d9-6a88e6042001.png)

**Comment by vpetrusevici** [comment]
![image](https://user-images.githubusercontent.com/40790510/145118202-7856833e-70b6-4fa8-ab6a-fadebfb7b6bd.png)
@RicoSuter  Thanks! But looks like this is still not a good solution for strict mode checking. Can we add also 'as any' in the end?

**Comment by RicoSuter** [comment]
@vpetrusevici wouldnt it be better to use `_observableOf(<any>null)` to support older TS versions?

**Comment by vpetrusevici** [comment]
@RicoSuter as you see in screenshot we already have both variants (<any>null and [] as any). So maybe it doesn't matter :)

**Comment by rhegner** [comment]
I experience the same issue with strict mode. Should we open a separate issue for this?

**Comment by lahma** [comment]
@rhegner try latest from MyGet feed (see README), it should contain the fix commit you can see above that was used to closet this issue.

**Comment by Zyberg** [comment]
Experiencing the same issue with `_observableOf(null)` when using NSwagStudio windows program to generate the API client.

**Comment by lahma** [comment]
Even with the just released 13.15.1? It seems that auto-update doesn't find it though... Studio installer is part of artifacts zip at the bottom of this page though: https://github.com/RicoSuter/NSwag/actions/runs/1560520361

**Comment by Zyberg** [comment]
Oh, it is fixed with 13.15.1! Thanks, the auto-update really didn't suggest me to install it.

**Comment by RicoSuter** [comment]
> Thanks, the auto-update really didn't suggest me to install it.

yeah sorry, forgot to upload the msi artifact (still need to do this manually).

**Comment by deceptiveSimplicity** [comment]
With NSwag 13.15.3 I still get errors like this when using Angular 13, RxJS 7 and strict mode.
```
protected processGetDevices(response: HttpResponseBase): Observable<DeviceBriefDto[]> {
    const status = response.status;
    const responseBlob =
        response instanceof HttpResponse ? response.body :
        (<any>response).error instanceof Blob ? (<any>response).error : undefined;

    let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
    if (status === 200) {
        return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
        let result200: any = null;
        let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
        if (Array.isArray(resultData200)) {
            result200 = [] as any;
            for (let item of resultData200)
                result200!.push(DeviceBriefDto.fromJS(item));
        }
        else {
            result200 = <any>null;
        }
        return _observableOf(result200);
        }));
    } else if (status !== 200 && status !== 204) {
        return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }));
    }
    return _observableOf<DeviceBriefDto[]>(<any>null);
}
```
The error is on the return statement.
`error TS2322: Type 'Observable<DeviceBriefDto>' is not assignable to type 'Observable<DeviceBriefDto[]>'.
  Type 'DeviceBriefDto' is missing the following properties from type 'DeviceBriefDto[]': length, pop, push, concat, and 28 more.`

**Comment by vpetrusevici** [comment]
@RicoSuter Hi. There is still a problem with array types. 
![image](https://user-images.githubusercontent.com/40790510/146241142-f2a344a6-d7a2-4dc5-ba11-c0217f3ba99d.png)

But looks like it works without types at all 
![image](https://user-images.githubusercontent.com/40790510/146241224-5ece6af0-75e1-4b1a-89cc-d8a5cc440c1a.png)

**Comment by msteel9999** [comment]
I'm trying to upgrade our project to Angular 16 and I can't get nswag to work with rxjs. I've tried various versions including 13.15.1
