### ISSUE TITLE
Version 14.0.1.0 - aspnetcore2openapi generate code where NSwagStudio will

### ISSUE THREAD

**Issue by haverjes** [RicoSuter/NSwag#4730]
I have a minimal api .net8 app and I need an automated way to generate an OpenApi file at build time (one without the Servers property).  I thought aspnetcore2openapi would be the ideal tool because Studio generates it from the project with no problem.  But when I run the console command I get the following error:

> Done executing command. Exit Code: 0.
Done executing command
Output:
AssemblyName: Miniter.Services.ImagingApi
OutputPath: bin\Debug\net8.0\
PlatformTarget:
Platform: AnyCPU
ProjectDepsFilePath: C:\Projects\Miniter\Miniter.Webs\Imaging\Miniter.Services.ImagingApi\bin\Debug\net8.0\Miniter.Services.ImagingApi.deps.json
ProjectDir: C:\Projects\Miniter\Miniter.Webs\Imaging\Miniter.Services.ImagingApi\
ProjectRuntimeConfigFilePath: C:\Projects\Miniter\Miniter.Webs\Imaging\Miniter.Services.ImagingApi\bin\Debug\net8.0\Miniter.Services.ImagingApi.runtimeconfig.json
TargetFileName: Miniter.Services.ImagingApi.dll
TargetFrameworkIdentifier: .NETCoreApp
System.InvalidOperationException: Unsupported target framework '.NETCoreApp'.
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiCommand.<RunAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessSingleAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NConsole.CommandLineProcessor.<ProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.NSwagCommandProcessor.<ProcessAsync>d__3.MoveNext()

**Comment by Bonuspunkt** [comment]
ran into the sam issue, using the correct executable
```xml
<Exec ... Command="$(NSwagExe_Net80) ..."/>
```
fixed it

**Comment by haverjes** [comment]
Thank you.  I could have sworn I tried that and got a different error.  But doing it this morning worked like a charm.

**Comment by Geraint87** [comment]
Could you please share the configuration you've used? I'm using $(NSwagExe_Net80) in the command, but still getting this error.
